// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fifvgsxcflsfrwamfroy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpZnZnc3hjZmxzZnJ3YW1mcm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTEwMTMsImV4cCI6MjA2OTAyNzAxM30.KH1sd20syp9wm7ZTYmjng2boAowBbtBrpx1uGX_JyTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});